
services:
  - type: web
    name: askpat
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python askpat_bot.py"
    envVars:
      - key: SLACK_BOT_TOKEN
        sync: false
      - key: SLACK_SIGNING_SECRET
        sync: false
    plan: free
